### PR TITLE
return bad request if IllegalArgumentException

### LINKED ISSUE #198: Unhandled exception in case of malformed session cookie (server returns 500 Internal Server Error)
### Expected Behavior

Micronaut server should not return 500 Internal Server Error in case of malformed session cookie in the request. It is incorrectly formatted request which should be categorized as 4xx.

### Actual Behaviour

Response 500 Internal Server Error is sent because of the unhandled exception:

```
Unexpected error occurred: Illegal base64 character 5f
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at io.micronaut.session.http.CookieHttpSessionIdGenerator.sessionIdFromCookie(CookieHttpSessionIdGenerator.java:77)
	at io.micronaut.session.http.CookieHttpSessionStrategy.resolveIds(CookieHttpSessionStrategy.java:78)
	at io.micronaut.session.http.HttpSessionFilter.doFilter(HttpSessionFilter.java:85)
	at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)
```

### Steps To Reproduce

- Run `ApplicationTest` in the example application

### Environment Information

_No response_

### Example Application

https://github.com/mancze/micronaut-sandbox/commit/9980567f6e6b32b2e71f8d3f42c07b25a78282e6

### Version

4.5.0

### PR DESCRIPTION
**Pull request by sdelamo**
Close: https://github.com/micronaut-projects/micronaut-session/issues/198

I am not sure if we should fix this in `micronaut-session`. I lean towards creating an `ExeptionHandler` in `Micronaut-core` for `IllegalArgumentException`. thoughts?

### CODE REVIEW

File: session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java [hunk 1]
```diff
@@ -81,19 +83,23 @@ public int getOrder() {
...
-                return encodeSessionId(request, storeSessionInAttributes);
+        try {
+            for (HttpSessionIdResolver resolver : resolvers) {
+                List<String> ids = resolver.resolveIds(request);
+                if (CollectionUtils.isNotEmpty(ids)) {
+                    String id = ids.get(0);
+                    Publisher<Optional<Session>> sessionLookup = Publishers.fromCompletableFuture(() -> sessionStore.findSession(id));
+                    Flux<MutableHttpResponse<?>> storeSessionInAttributes = Flux
+                            .from(sessionLookup)
+                            .switchMap(session -> {
```
Comment (graemerocher) [inline session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java:94]:
```suggestion
                    Mono<MutableHttpResponse<?>> storeSessionInAttributes = Mono
                            .fromFuture(() -> sessionStore.findSession(id)))
                            .map(session -> {
```

File: session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java [hunk 2]
```diff
@@ -81,19 +83,23 @@ public int getOrder() {
...
+                                session.ifPresent(entries -> request.getAttributes().put(SESSION_ATTRIBUTE, entries));
+                                return chain.proceed(request);
+                            });
+                    return encodeSessionId(request, storeSessionInAttributes);
+                }
             }
+        } catch (IllegalArgumentException e) {
+            return Flux.error(new HttpStatusException(HttpStatus.BAD_REQUEST, e.getMessage()));
```
Comment (graemerocher) [inline session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java:102]: may as well just throw the exception

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java (hunk 2 above)
Comment (sdelamo) [reply session/src/main/java/io/micronaut/session/http/HttpSessionFilter.java:102]: that is what the user complains about. 

@mancze :
> Micronaut server should not return 500 Internal Server Error in case of malformed session cookie in the request. It is incorrectly formatted request which should be categorized as 4xx.

He thinks we should not return a 500 for a `IllegalArgumentException` and we should return a 400 or maybe a 422. 

I think we should fix this in core with a new `ExceptionHandler` for `IllegalArgumentException`. What do you think @dstepanov ?

**Review by graemerocher — APPROVED** [review]
